export enum ButtonColor {
	DARK = 'dark',
	WHITE = 'white',
	SUCCESS = 'success',
	SUCCESS_ALT = 'success-alt',
	INFO = 'info',
	INFO_ALT = 'info-alt',
	WARN = 'warning',
	WARN_ALT = 'warning-alt',
	ERROR = 'warning',
	ERROR_ALT = 'warning-alt',
	GREY = 'grey',
	GREY_ALT = 'grey-alt',
	PRIMARY = 'primary',
	PRIMARY_ALT = 'primary-alt',
	ACCENT = 'accent',
	ACCENT_ALT = 'accent-alt',
}
